### ISSUE TITLE
Do we have python version of the three tutorials?

### ISSUE THREAD

**Issue by HelloWorldLTY** [quon-titative-biology/scProjection#1]
Hi, thanks for your great work! I notice that there is a python version for this tool, and only tutorial 4 has the python version. Do you have plan to change tutorials 1-3 as python format? Thanks a lot.

**Comment by UCDNJJ** [comment]
Hi @HelloWorldLTY, we do plan to change the tutorials 1-3 into python and make interacting with the scProjection model class more user-friendly. Keep an eye out for the next update in a week or 2.

**Comment by HelloWorldLTY** [comment]
Sounds good, thanks a lot.

**Comment by HelloWorldLTY** [comment]
Moreover, I met bugs in installing scProjection

Collecting sklearn
  Downloading sklearn-0.0.post7.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I suggest to replace "sklearn" with "scikit-learn". Do you think it is a good idea? Thanks.

**Comment by hongruhu** [comment]
@HelloWorldLTY Hi, I agree that we need to use pip install scikit-learn instead as the sklearn PyPI package is deprecated

**Comment by simomounir** [comment]
Any news on this front? Python scripts for the examples?

Thanks :)

**Comment by hongruhu** [comment]
> Any news on this front? Python scripts for the examples?
> 
> Thanks :)
hi @simomounir , you could follow this tutorial and apply scProjection on your own data in python: https://github.com/quon-titative-biology/examples/blob/master/scProjection_imputation/readme.md
